<a href="https://colab.research.google.com/github/JoaoJuliasz/Projeto-WebScraping-BeautifulSoup/blob/master/Projeto_WebScraping_BeautifulSoup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#Importando as Libs
import pandas as pd
from urllib.request import urlopen
from urllib.request import HTTPError
from urllib.request import URLError
from bs4 import BeautifulSoup

#URL base
url = 'https://www.imdb.com/chart/top?ref_=nv_mv_250'

#Tratando error da url

try:
  html = urlopen(url)
except HTTPError as e:
  print(e)
except URLError as e:
  print('The server could not be found!')

#Enfim monstrando o poder da bs4
bs = BeautifulSoup(html, 'lxml')

#Imprimindo o titulo da pagina
movies = bs.select('.lister-list tr')

titles = []
directors_writers = []
years = []
ratings = []

for movie in movies:
    titles.append(movie.find('td', class_='titleColumn').find('a').get_text())
    directors_writers.append(movie.find('td', class_='titleColumn').find('a')['title'])
    years.append(movie.find('td', class_='titleColumn').find('span').get_text()[1:5])
    ratings.append(movie.find('td', class_='imdbRating').find('strong').get_text())

#Criando tabela com DataFrame
df = pd.DataFrame({
    'title': titles,
    'year' : years,
    'rating': ratings,
    'director_and_writers': directors_writers
})
df.head()

#Salvando dados em arquivo csv
#df.to_csv('imdb_best_movies.csv')

                        title  ...                               director_and_writers
0    The Shawshank Redemption  ...  Frank Darabont (dir.), Tim Robbins, Morgan Fre...
1               The Godfather  ...  Francis Ford Coppola (dir.), Marlon Brando, Al...
2      The Godfather: Part II  ...  Francis Ford Coppola (dir.), Al Pacino, Robert...
3             The Dark Knight  ...  Christopher Nolan (dir.), Christian Bale, Heat...
4                12 Angry Men  ...      Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb
..                        ...  ...                                                ...
245       The Invisible Guest  ...       Oriol Paulo (dir.), Mario Casas, Ana Wagener
246                   Aladdin  ...  Ron Clements (dir.), Scott Weinger, Robin Will...
247         Castle in the Sky  ...  Hayao Miyazaki (dir.), Anna Paquin, James Van ...
248           Song of the Sea  ...    Tomm Moore (dir.), David Rawle, Brendan Gleeson
249   Guardians of the Galaxy  ...         James Gunn (dir.), Chris Pratt, Vin Diesel

[250 rows x 4 columns]